# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-11-03 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20191103_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_set', to='qa.Question'),
        ),
    ]
